#!/bin/sh

. ./clean

mkdir target;

printf "Compiling simsrvTest... ";
####################################
clang -o target/simsrvTest          \
      -std=c11                       \
                                      \
      simsrvTest.c GLFW/libglfw3.a     \
                                        \
      -lm -lGL -lX11 -lXxf86vm           \
      -lpthread -lXrandr -lXi             \
###########################################
printf "Done.\n\n";



printf "Compiling SOIL... ";
##############################################
mkdir target/SOIL;                           #
for file in $(ls SOIL/*.c); do               #
	clang -c -o target/${file}.o $file   #
done                                         #
ar cr target/SOIL.a $(ls target/SOIL/*.o)    #
##############################################
printf "Done.\n\n";


printf "Compiling r2dTest.o... ";
##################################
clang -o target/r2dTest           \
      -std=c11                     \
                                    \
      r2dTest.c                      \
                                      \
      GLFW/libglfw3.a                  \
      target/SOIL.a                     \
                                         \
      -lm -lGL -lX11 -lXxf86vm            \
      -lpthread -lXrandr -lXi              \
############################################
printf "Done.\n\n";

printf "./target contains:\n";
ls -1 target;
