#!/bin/sh

mkdir target;

clang -o target/r2dTest             \
      -std=c11                       \
                                      \
      r2dTest.c GLFW/libglfw3.a        \
                                        \
      -lm -lGL -lX11 -lXxf86vm           \
      -lpthread -lXrandr -lXi             \


