#!/bin/sh

mkdir target;

####################################
clang -o target/simsrvTest          \
      -std=c11                       \
                                      \
      simsrvTest.c GLFW/libglfw3.a     \
                                        \
      -lm -lGL -lX11 -lXxf86vm           \
      -lpthread -lXrandr -lXi             \
###########################################

